## 4차

#### 1. . 탐색적 데이터 분석
    -    유의미한 데이터간의 관계를 찾고 검증하기 위하여 데이터의 기본 통계와 데이터 분포를 분석하고 
         데이터 변수간 관계를 확인하는 능력이다.

#### 3. 넘파이와 리스트의 차이
     : numpy와 list는 거의 동일하지만 numpy는 배열의 특징을 갖는다.
       많은 숫자 데이터를 하나의 변수에 넣고 관리 할 때 리스트는 속도가 느리고 메모리를 많이 차지하는 단점이 있다. 
       배열(array)을 사용하면 적은 메모리로 데이터를 빠르게 처리할 수 있다. 배열은 리스트와 비슷하지만 다음과 같은 점에서 다르다.
       배열의 특징이란 모든 원소가 같은 자료형이어야 하고 원소의 갯수를 바꿀 수 없다.    

#### 4. 넘파이 기초통계 구하는 함수들

     mean() : 평균
     median() : 중앙값
     var() : 분산
     std() : 표준편차


In [26]:
import numpy as np
data=[1,5,8,2,9,4,41,62,34,235]
data2=np.array(data)
print(np.mean(data2))
print(np.median(data2))
print(np.var(data2))
print(np.std(data2))

40.1
8.5
4601.6900000000005
67.83575753244007


#### 5. Numpy 벡터연산


In [123]:
data=[1,2,3,4,5,6,7,8]
data2=np.array(data)
print(data2*3)


[ 3  6  9 12 15 18 21 24]


#### 6. 넘파이 fancy 인덱싱
      :팬시 인덱싱은 정수나 불린(Boolean) 값을 가지는 다른 Numpy 배열로 배열을 인덱싱할 수 있는 기능


In [36]:
#인덱싱
data3=np.array([[[11,12,13],[14,15,16],[17,18,19]],
              [[21,22,23],[24,25,26],[27,28,29]]])
print(data3)
data3[0][1]


[[[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


array([14, 15, 16])

In [39]:
a = np.array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'])
index = np.array([1, 4, 5])
print(a[index])


['b' 'e' 'f']


In [40]:
# fancy indexing

arr=np.array([i for i in range(10)])

idx=np.array([True,False,True,False,True,False,True,False,True,False])

print(arr[idx])
print(arr%2)
print(arr%2 ==0 )
print(arr[arr%2==0])

print("---------------------------")
#arr에서 3의 배수를 찾아라
print(arr[arr%3==0])

#arr에서 4로 나누면 1이 남는 수를 찾아라
print(arr[arr%4==1])

#arr에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라
print(arr[(arr%3==0) & (arr%4==1)])

[0 2 4 6 8]
[0 1 0 1 0 1 0 1 0 1]
[ True False  True False  True False  True False  True False]
[0 2 4 6 8]
---------------------------
[0 3 6 9]
[1 5 9]
[9]


#### 7. 브로드캐스트개념
    : 벡터(또는 행렬)끼리 덧셈 혹은 뺄셈을 하려면 두 벡터(또는 행렬)의 크기가 같아야 한다. 
      NumPy에서는 서로 다른 크기를 가진 두 배열의 사칙 연산도 지원한다. 
      이 기능을 브로드캐스팅(broadcasting)이라고 하는데 크기가 작은 배열을 자동으로 반복 확장하여 크기가 큰 배열에 맞추는 방법이다.

In [125]:
print([i for i in range(5)])
print([[i] for i in range(5)])
print([range(7)[i:i+3] for i in range(5)])

[0, 1, 2, 3, 4]
[[0], [1], [2], [3], [4]]
[range(0, 3), range(1, 4), range(2, 5), range(3, 6), range(4, 7)]


In [130]:
x= np.vstack([range(7)[i:i+3] for i in range(5)])
y=np.arange(5)[:, np.newaxis]
print(x+y)


[[ 0  1  2]
 [ 2  3  4]
 [ 4  5  6]
 [ 6  7  8]
 [ 8  9 10]]


#### 8. 판다스의 대표적인 자료구조
      - Series : 값과 인덱스를 묶어서 하나의 구조로 만든것
      - DataFrame : 테이블

#### 9. indexer
     -loc  : 라벨값 기반의 2차원 인덱싱을 지원하는 인덱서
            #loc는 행을 기준으로 하기 때문에 열로 할 수 없다.
     -iloc : 순서를 나타내는 정수기반의 2차원 인덱서
     - at: 라벨값 기반의 2차원 인덱싱 (한개의 스칼라 값만 찾는다)
     - iat : 순서를 나타내는 정수 기반의 2차원 인덱싱 (한개의 스칼라 값만 찾는다)

#### 10. 다중인덱스
      - ????

#### 1. Numpy 영화 평점

In [2]:
import numpy as np
movie=np.loadtxt('ratings.dat',delimiter='::',dtype=np.int64)
movie

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]], dtype=int64)

In [14]:
#21행부터 30행까지 userid와 movie,id 만 출력
movie[21:31,0:2]

#전체 평점평균구하기
movie[:,2].mean()
sum(movie[:,2])/len(movie)
np.mean(movie[:,2])

3.581564453029317

In [16]:
# 사용자별 평점 평균(10명만 출력)
user_id=np.unique(movie[:,0])
mean_value=[]

for id in user_id:
    data_user=movie[movie[:,0]==id, :]
    value=data_user[:,2].mean()
    mean_value.append([id,value])
print("결과: ", mean_value[:11])

#최고평점구하기
arr_mean_values=np.array(mean_value)
print(np.argmax(arr_mean_values[:,1]))   # 최댓값의 위치

#사용자별 평점 평균 데이터를 파일로 저장
arr_mean_values=np.array(mean_value)
print(type(arr_mean_values))

#np.savetxt('data/movie/id_ration.csv', arr_mean_values, delimiter=',',
          #fmt='%.1f'

KeyboardInterrupt: 

#### 2. 시리즈에서 특정데이터(500보다 크고 100보다 작은)를 찾는 방법

In [48]:
import pandas as pd
idx=['가','나','다','라','마','바','사']
s=pd.Series([160,600,300,200,90,14,50],index=idx)
s.index.name='한글'
s[(s > 500) |(s < 100)]

한글
나    600
마     90
바     14
사     50
dtype: int64

#### 3. 시리즈에서 인덱스와 값을 출력하는 방법


In [31]:
s.index
s.values

array([160, 400, 300, 200,  90,  14,  50], dtype=int64)

#### 4. 춘향 성적

In [66]:
import pandas as pd
# 1. 인덱스를 춘향, 몽룡, 향단, 방자로 구성된 데이터프레임 df를 작성하시
data={
    '국어':[80,90,70,30],
    '영어':[90,70,60,40],
    '수학':[90,60,80,70]
}
idx=['춘향','몽룡','향단','방자']
col=['국어','수학','영어']
df=pd.DataFrame(data,index=idx,columns=col)
df

국어  수학  영어
춘향  80  90  90
몽룡  90  60  70
향단  70  80  60
방자  30  70  40

In [68]:
# 2. 모든 학생의 수학점수를 나타내시오
df['수학']

# 3. 모든 학생의 국어와 영어 점수를 나타내시오
df[['국어','영어']]

# 4. 모든 학생의 각 과목 평균 점수를 새로운 열로 추가하시오.
df['평균']=((df['국어']+df['수학']+df['영어'])/3).round(2)

# 5. 방자의 영어점수를 80점으로 수정하고 평균 점수도 다시 수정하시오
df['영어']['방자']=80
df
# 6. 춘향의 점수를 데이터 프레임으로 나타내시오
df[:1]

# 7. 향단의 점수를 Series로 나타내시오.
df.T['향단']

C:\Users\ZENBOOK\anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()


국어    70.0
수학    80.0
영어    60.0
평균    70.0
Name: 향단, dtype: float64

#### 5. 판다스 도시별 과일가격 실습문제

In [161]:
df = pd.DataFrame({
    'city': ['부산', '부산', '부산', '부산', '서울', '서울', '서울'],
    'fruits': ['apple', 'orange', 'banana', 'banana', 'apple', 'apple', 'banana'],
    'price': [100, 200, 250, 300, 150, 200, 400],
    'quantity': [1, 2, 3, 4, 5, 6, 7]
},index=[1,2,3,4,5,6,7])
df

city  fruits  price  quantity
1   부산   apple    100         1
2   부산  orange    200         2
3   부산  banana    250         3
4   부산  banana    300         4
5   서울   apple    150         5
6   서울   apple    200         6
7   서울  banana    400         7

In [164]:
# 도시별로 과일의 가격 평균과 수량 평균을 구해보시오
df.groupby('city').mean()

# 도시별, 과일별 가격평균과 수량평균을 구해보시오
df.groupby([df.city,df.fruits]).mean()

# 위의 문제에서 도시별, 과일별 라벨을 인덱스로 하고싶지 않을 경우
df.groupby([df.city,df.fruits],as_index=False).mean()

# 도시별로 가격의 평균과 수량의 합계를 동시에 구하고자 했을 때
df.groupby(df.city).agg([np.mean,np.sum])

price      quantity    
       mean  sum     mean sum
city                         
부산    212.5  850      2.5  10
서울    250.0  750      6.0  18

## 5차

#### 1. 통계 기반 데이터 분석 
     수집된 내·외부 데이터 및 정형·비정형 데이터를 활용하여 분석 목적에 따라 가설을 설정하고 필요한 데이터셋 을 편성하여 
     통계기반 데이터 분석 모델을 만들고 평가하는 능력이다.


#### 3. 판다스에서 카테고리별 개수 세는 법 
    - value_counts(): 카테고리별로 갯수 세기  (데이터프레임이 아니라 시리즈에서 사용)
      데이터프레임에서 이 함수를 사용하고 싶으면 데이터프레임을 열로 뽑아서 시리즈로 만들어줘야한다.

In [113]:
np.random.seed(1)

s=pd.Series(np.random.randint(6,size=100))
s.head(10)

s.value_counts()

1    22
0    18
4    17
5    16
3    14
2    13
dtype: int64

#### 4. 정규표현식
     - 일종의 문자를 표현하는 공식, 특정 규칙이 있는 문자열 집합을 추출할 때 자주 사용하는 기법
       복잡한 문자열을 처리할 때 사용하는 기법

#### 5,6,7. 다중인덱스 
    -??????

#### 8.정규표현식

#### 9.데이터프레임 병합


In [112]:
pd.merge(df1, df2)                           -> inner join
pd.merge(df1, df2, how='outer')         -> outer join
pd.merge(df1, df2, how='left')            -> left outer join
pd.merge(df1, df2, how='right')          -> right outer join

pd.concat([s1, s2])                            -> 행병합
pd.concat([df1, df2], axis=1)               -> 열병합

SyntaxError: invalid syntax (<ipython-input-112-ce308c8bfd32>, line 1)

#### 10.groupby 에서 사용할 수 있는 연산메서드
    - size(),count() : 갯수
      mean(),median(),min(),max()
      sum(),prod(),std(),var(),quantile()
      first(),last()
      agg(),aggregate()
      describe()
      apply()
      transform()


#### 1.시리즈 만들기

In [70]:
a=pd.Series([123,456,789],index=['가','나','다'])
a

idx=['a','b','c','d','e']
b=pd.Series([100,200,300,400,500],index=idx)
b

a    100
b    200
c    300
d    400
e    500
dtype: int64

#### 2. 데이터프레임에서 행의 합계

In [116]:
np.random.seed(1)
df = pd.DataFrame(np.random.randint(10, size = (4, 8)))
df



#열의합계
df.sum()
df.sum(axis=0)
df.loc['cosum',:]=df.sum()  
df


#행의합계
df.sum(axis=1)
df['rowsum']=df.sum(axis=1)
df

0     1     2     3     4     5    6     7  rowsum
0       5.0   8.0   9.0   5.0   0.0   0.0  1.0   7.0    35.0
1       6.0   9.0   2.0   4.0   5.0   2.0  4.0   2.0    34.0
2       4.0   7.0   7.0   9.0   1.0   7.0  0.0   6.0    41.0
3       9.0   9.0   7.0   6.0   9.0   1.0  0.0   1.0    42.0
cosum  24.0  33.0  25.0  24.0  15.0  10.0  5.0  16.0   152.0

#### 3,4. tips예제

In [78]:
import seaborn as sns
tips=sns.load_dataset('tips')
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [158]:
# 식사대금과 팁의 비율을 나타내는  tip_pct를 추가
tips['tip_pct']=tips['tip']/tips['total_bill']*100
tips


# 성별로 인원수 파악
tips.groupby('sex').count()
tips.groupby('sex').size()


# 성별, 흡연 유무별로 인원수 파악
tips.groupby(['sex','smoker']).count()
tips.groupby(['sex','smoker']).size()


# 성별인원수와 성별,흡연유무별로 인원수 파악한 두 정보를 하나의 테이블로 출력
tips.pivot_table(values='tip_pct',index=['sex','smoker'],aggfunc='count',margins=True)


#성별에 따른 팁 비율
tips.groupby('sex')[['tip_pct']].mean()
tips.pivot_table('tip_pct','sex')


#흡연유무에 따른 팁 비율
tips.groupby('smoker')[['tip_pct']].mean()
tips.pivot_table('tip_pct','smoker')


#팁의 비율이 요일과 점심/저녁 여부, 인원수에 어떤 영향을 받는지 분석
tips.groupby(['day','time','size'])[['tip_pct']].mean().dropna().round(2)
tips.pivot_table('tip_pct',['day','time','size'])


# 성별,흡연 유무별로 가장 많은 팁과 가장 적은 팁의 차이
def tiptip(x):
    return x.max()-x.min()

tips.groupby(['sex','smoker'])[['tip']].apply(tiptip)


# 성별과 날짜를 기준. 흡연자 유무를 따져서 팁비율과 size출력
tips.groupby(['sex','day','smoker'])[['tip_pct','size']].mean()
tips.pivot_table(['tip_pct','size'],['sex','day','smoker'])
tips.pivot_table(['tip_pct','size'],['sex','day'],'smoker')

size              tip_pct           
smoker            Yes        No        Yes         No
sex    day                                           
Male   Thur  2.300000  2.500000  16.441676  16.570635
       Fri   2.125000  2.000000  14.473025  13.800498
       Sat   2.629630  2.656250  13.906681  16.213217
       Sun   2.600000  2.883721  17.396381  15.829067
Female Thur  2.428571  2.480000  16.307257  15.597147
       Fri   2.000000  2.500000  20.912912  16.529591
       Sat   2.200000  2.307692  16.381673  14.799347
       Sun   2.500000  3.071429  23.707473  16.570992

#### 5.시계열데이터

In [ ]:
data_str=['2020, 1, 1','2020, 1,4','2020, 1, 6','2020, 1, 9']
aa=pd.to_datetime(data_str)
aa


# 날짜를 인덱스로 활용
np.random.seed(0)
s=pd.Series(np.random.randn(4))
s


#날짜 데이터 생성
pd.date_range('2020-1-1','2020-4-30')    #1월1일부터 4월30일까지
pd.date_range('2020-4-1',periods=30)   # 4월1일부터 30일동안의 날짜




In [97]:
data = {
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "지역": ["수도권", "경상권", "수도권", "경상권"],
    "2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]
}
print(type(data))
print(data)
df=pd.DataFrame(data)
df

<class 'dict'>
{'2015': [9904312, 3448737, 2890451, 2466052], '2010': [9631482, 3393191, 2632035, 2431774], '2005': [9762546, 3512547, 2517680, 2456016], '2000': [9853972, 3655437, 2466338, 2473990], '지역': ['수도권', '경상권', '수도권', '경상권'], '2010-2015 증가율': [0.0283, 0.0163, 0.0982, 0.0141]}


2015     2010     2005     2000   지역  2010-2015 증가율
0  9904312  9631482  9762546  9853972  수도권         0.0283
1  3448737  3393191  3512547  3655437  경상권         0.0163
2  2890451  2632035  2517680  2466338  수도권         0.0982
3  2466052  2431774  2456016  2473990  경상권         0.0141

In [112]:
df=pd.DataFrame(data,columns=['지역','2000','2005','2010','2015','2010-2015 증가율'])

df['지역']
df[['지역']]
df[['2005','2010']]
df[['2005','2010']][:2]

2005     2010
0  9762546  9631482
1  3512547  3393191

In [111]:
df=pd.DataFrame(np.random.randint(5,size=(4,4)),dtype=float)
print(df)
np.random.seed(0)

s=pd.Series(np.random.randint(6,size=100))
s.head()

s.value_counts()

df=pd.DataFrame(np.random.randint(100,size=(10,10)))
df

     0    1    2    3
0  4.0  3.0  3.0  0.0
1  0.0  1.0  0.0  3.0
2  2.0  0.0  4.0  0.0
3  1.0  3.0  3.0  4.0


0   1   2   3   4   5   6   7   8   9
0  50  36  34  48  93   3  98  42  77  21
1  73   0  10  43  58  23  59   2  98  62
2  35  94  67  82  46  99  20  81  50  27
3  14  41  58  65  36  10  86  43  11   2
4  51  80  32  54   0  38  19  46  42  56
5  60  77  30  24   2   3  94  98  13  40
6  72  19  95  72  26  66  52  67  61  14
7  96   4  67  11  86  77  75  56  16  24
8  29  21  25  80  60  61  83  33  32  70
9  85  31  13  71  56  24  79  41  18  40